---
title: "Graphing demographic with asthma"
author: "Ava"
date: '(`r format(Sys.time(), "%B %d, %Y")`)'
output: 
  github_document: default
  html_notebook: default 
---

```{r}
# tidyverse packages
library(dplyr)       # data wrangling
library(readr)       # read/write tabular data
library(stringr)     # work with strings
library(tidyr)       # data wrangling
# spatial packages
library(janitor)     # data wrangling
library(sf)          # spatial data tools
library(mapview)     # projections
library(tigris)      # census data wrangling 
# other packages
library(here)        # file path management
library(naniar)      # missing data
library(ggplot2)
library(viridis)      # palettes
library(leaflet)
library(tidycensus) 
library(sp)
library(ggplot2)   
library(RColorBrewer)  # color palettes
library(viridis)       # color palettes
```


```{r}
csv_pov <- read_csv(here("data", "csv", "poverty 2.csv"))
```

```{r}
ggplot(csv_pov, aes(x = density, y = count))+ geom_point(shape = 21)+
            labs(x = "poverty", y = "asthma") +
   geom_smooth(method='lm')
```

trying with shapefile 

```{r}
shapefile_pov <- st_read(here("data","csv", "poverty", "poverty.shp"), stringsAsFactors = FALSE)
```

```{r}
ggplot(shapefile_pov, aes(x = density, y = count))+ geom_point(shape = 21)+
            labs(x = "poverty", y = "asthma") +
   geom_smooth(method='lm')
```
```{r}
shapefile_income <- st_read(here("data","csv", "median_income", "median_income.shp"), stringsAsFactors = FALSE)
```


```{r}
ggplot(shapefile_income, aes(x = estimate_x, y = count))+ geom_point(shape = 21)+
            labs(x = "median income", y = "asthma") +
  geom_smooth(method='lm')
```

```{r}
shapefile_medicaid <- st_read(here("data","csv", "medicaid", "medicaid.shp"), stringsAsFactors = FALSE)
```
```{r}
ggplot(shapefile_medicaid, aes(x = percent, y = count))+ geom_point(shape = 21)+
            labs(x = "medicaid", y = "asthma") +
   geom_smooth(method='lm')
```


```{r}
shapefile_aa <- st_read(here("data","csv", "precent_aa", "precent_aa.shp"), stringsAsFactors = FALSE)
```

```{r}
ggplot(shapefile_aa, aes(x = percent, y = count))+ geom_point(shape = 21)+
            labs(x = "Percent African American", y = "asthma") +
   geom_smooth(method='lm')
```

```{r}
shapefile_home <- st_read(here("data","csv", "home_value", "home_value.shp"), stringsAsFactors = FALSE)
```
```{r}
ggplot(home_metro, aes(x = estimate.x, y = count))+ geom_point(shape = 21)+
            labs(x = "median home value", y = "asthma") +
   geom_smooth(method='lm')
```


